# Generated by Django 3.2 on 2022-08-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_image', models.TextField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('date_published', models.DateTimeField()),
            ],
        ),
    ]
